
- name : 06b Play to Configure MKA CKN and CAK
  hosts: iosxe
  connection: netconf
  gather_facts: false

  vars_files:
    - ~/clus2023-devnet-2111/vaults/ciscolive.vault
  tasks:
    - name: 06b Task to Configure MKA CKN and CAK
      netconf_config:
        xml: |
            <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
              <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
                <key>
                  <chain xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-crypto">
                    <name>MACSEC-KEY</name>
                    <macsec/>
                    <key>
                      <id>1234</id>
                      <cryptographic-algorithm-choice>
                        <macsec>aes-256-cmac</macsec>
                      </cryptographic-algorithm-choice>
                      <key-string>
                        <encryption>0</encryption>
                        <key>1234567812345678123456781234567812345678123456781234567812345678</key>
                      </key-string>
                    </key>
                  </chain>
                </key>
              </native>
            </config>

