
- name : 06c Play to Configure MKA Policy
  hosts: iosxe
  connection: netconf
  gather_facts: false

  vars_files:
    - ~/clus2023-devnet-2111/vaults/ciscolive.vault

  tasks:
    - name: 06c Task to Configure MKA Policy
      netconf_config:
        xml: |
            <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
              <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
                <mka>
                  <policy xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-mka">
                    <name>MKA_G-1-0-1</name>
                    <macsec-cipher-suite>gcm-aes-256</macsec-cipher-suite>
                  </policy>
                  <suppress xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-mka">
                    <syslogs>
                      <sak-rekey>true</sak-rekey>
                    </syslogs>
                  </suppress>
                </mka>
              </native>
            </config>

