
- name : 06d Play to Configure Interface Description
  hosts: iosxe
  connection: netconf
  gather_facts: false

  vars_files:
    - ~/clus2023-devnet-2111/vaults/ciscolive.vault

  tasks:
    - name: 06d Task to Configure Interface Description
      netconf_config:
        xml: |
            <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
              <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
                <interface>
                  <GigabitEthernet>
                    <name>1/0/1</name>
                    <description>MACsec Encrypted Link</description>
                  </GigabitEthernet>
                </interface>
              </native>
            </config>

