---
- name: 06e Play to Configure the Interface with the MKA Policy
  hosts: iosxe
  connection: netconf
  gather_facts: false

  vars_files:
    - ~/clus2023-devnet-2111/vaults/ciscolive.vault

  tasks:
    - name: 06e Task to Configure the Interface with the MKA Policy
      netconf_config:
        xml: |
            <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
              <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
                <interface>
                  <GigabitEthernet>
                    <name>1/0/1</name>
                    <mka xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-mka">
                      <policy>
                        <name>MKA_G1-0-1</name>
                      </policy>
                    </mka>
                  </GigabitEthernet>
                </interface>
              </native>
            </config>

