---
- name : 06f Play to Configure the Interface with the MKA Key
  hosts: iosxe
  connection: netconf
  gather_facts: false

  vars_files:
    - ~/clus2023-devnet-2111/vaults/ciscolive.vault

  tasks:
    - name: 06f Task to Configure the Interface with the MKA Key
      netconf_config:
        xml: |
            <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
              <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
                <interface>
                  <GigabitEthernet>
                    <name>1/0/1</name>
                    <mka xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-mka">
                      <pre-shared-key>
                        <key-chain>
                          <name>MACSEC-KEY</name>
                        </key-chain>
                      </pre-shared-key>
                    </mka>
                  </GigabitEthernet>
                </interface>
              </native>
            </config>

