---
- name : NETCONF playbook
  hosts: iosxe
  connection: netconf
  gather_facts: false

  vars_files:
    - ~/clus2023-devnet-2111/vaults/ciscolive.vault

  tasks:
    - name: NETCONF RPC
      netconf_config:
        xml: |
            <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
              <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
                <interface>
                  <GigabitEthernet>
                    <name>1/0/1</name>
                    <macsec-option xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-switch">
                      <macsec>
                        <network-link/>
                      </macsec>
                    </macsec-option>
                  </GigabitEthernet>
                </interface>
              </native>
            </config>

